# -*- coding: utf-8 -*-
"""Tutorial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15W3gNhgRu-PwbGSDHKUOJ98r1-WhhLx4
"""

print("STEP 1: Installing package from GitHub...")
!pip install -q --no-cache-dir -U git+https://github.com/mschongchulshin/finetuningcadtest20250909.git
print("Installation complete.")
print("\n" + "="*50 + "\n")

print("STEP 2: Importing and running the generator...")
from cad_generator import CADGenerator

prompt = """
작업 공간 도면을 그려줘. 격자 1칸=10×10, 원점은 로봇 R1의 위치(0,0).
로봇은 2대(R1: (0,0), R2: (48, -8))를 파란 원으로 표시하고, 각 로봇의 최대 리치를 빨간 원으로,
작업각도는 주황색 부채꼴로 간단히 표현해줘(정확한 호 길이보다 영역이 보이도록).
컨베이어는 세 개: C1은 (-10, -20)에서 세로로 길게, C2는 (23, -7)에서 가로로 길게,
C3는 (50, -28)에서 세로로 아래쪽(-Y) 진행처럼 초록 네모로 그려줘.
테이블은 네 개: T1(-6, -10), T2(10, -6), T3(36, -8), T4(52, -20)을 회색 네모로 표시하고
안전펜스는 F1(-1, -10), F2(-1, -10) 두 개 직사각형을 검정 테두리로 둘러줘.
라벨(R1, R2, C1~C3, T1~T4, F1~F2)만 붙이면 돼. 대략적 비율만 맞춰도 괜찮아.
"""

print("Initializing generator... (Loading model from Hugging Face Hub)")
generator = CADGenerator()
print("Generator ready.")

print("\nGenerating JSON from the prompt...")
result_json_str = generator.generate(prompt)

print("\n--- Generated JSON ---")
print(result_json_str)

print("CAD 생성을 위한 프롬프트를 입력한 후 Enter를 누르십시오.")
user_prompt = input("Prompt: ")

if user_prompt and user_prompt.strip():
    print("\n" + "-"*50)
    print("입력된 프롬프트로 JSON 생성을 시작합니다...")

    generated_json = generator.generate(user_prompt)

    print("\n[생성된 JSON 결과]")
    print(generated_json)
    print("-"*50)
else:
    print("\n입력된 내용이 없어 실행을 취소했습니다.")
